spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:TPO-TEST;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:/db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect