### CREATE ACCOUNT
POST http://localhost:8082/api/v1/accounts/
Content-Type: application/json

{
  "username": "testusername2",
  "email": "testemail3@gop.com",
  "balance": 20,
  "currencyCode": "usd"
}

### UPDATE ACCOUNT
PUT http://localhost:8082/api/v1/accounts/
Content-Type: application/json

{
  "accountId": 2,
  "username": "testusernamewwww1",
  "email": "testemail2@gop.com",
  "balance": 0,
  "currencyCode": "usd"
}

### GET ACCOUNT
GET http://localhost:8082/api/v1/accounts/1/

### GET TRANSACTIONS
GET http://localhost:8082/api/v1/accounts/1/transactions/

### CREATE TRANSACTIONS
POST  http://localhost:8082/api/v1/accounts/1/transactions/
Content-Type: application/json

{
    "toAccountId": 8,
    "amount": "10",
    "currencyCode": "usd",
    "message" : "transfer title 1"
}